# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\x06stream\"-\n\x0c\x43ountRequest\x12\x0e\n\x06number\x18\x01 \x01(\x01\x12\r\n\x05steps\x18\x02 \x01(\x05\")\n\nCountReply\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0c\n\x04step\x18\x02 \x01(\x05\x32I\n\x0e\x43ounterService\x12\x37\n\x07\x43ountUp\x12\x14.stream.CountRequest\x1a\x12.stream.CountReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTREQUEST']._serialized_start=24
  _globals['_COUNTREQUEST']._serialized_end=69
  _globals['_COUNTREPLY']._serialized_start=71
  _globals['_COUNTREPLY']._serialized_end=112
  _globals['_COUNTERSERVICE']._serialized_start=114
  _globals['_COUNTERSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
